name: schedule_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^5.0.4
  dio: ^5.0.2
  flutter_svg: ^2.0.2
  table_calendar: ^3.0.8
  gap: ^2.0.0
  intl: ^0.17.0
  timelines: ^0.1.0
  shared_preferences: ^2.0.18
  alarm: ^0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/noLessons.svg
    - assets/no-connection.svg
    - assets/icon.png
    - assets/sample.mp3
    - assets/sample2.mp3
    - assets/sample3.mp3

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
        - weight: 700
        - asset: fonts/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: fonts/Montserrat-Regular.ttf
        - weight: 400
        - asset: fonts/Montserrat-Light.ttf
        - weight: 300